import { Cairo } from "next/font/google";
import "./globals.css";
import Navbar from "@/components/organisms/Navbar/Navbar";
import MovingLines from "@/components/pages/MovingLines/MovingLines";
const inter = Cairo({ subsets: ["latin"] });

export const metadata = { title: "masjid", description: "Generated by Shadow" };

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className={inter.className}>
        <Navbar />
        {children}
        <MovingLines />
      </body>
    </html>
  );
}
